### ISSUE TITLE
Wrong usage of `Fade` component

### ISSUE THREAD

**Issue by morellodev** [SPSIgnite/SPSIgnite.github.io#1]
Hi! I was just looking around and I found an incorrect usage of the **react-awesome-reveal** `Fade` component: https://github.com/SPSIgnite/SPSIgnite.github.io/blob/master/src/App.js#L3

You are importing the default export of the library, which by default renders a fading entrance from the left (which is what you wanted I guess), but that is used for custom animations. What you meant to do is importing the named export `Fade`:

```jsx
import { Fade } from "react-awesome-reveal";
```

Refer to the [docs](https://github.com/dennismorello/react-awesome-reveal#react-awesome-reveal) for the correct usage of the animated components!

Cheers.

**Comment by harens** [comment]
Thanks so much @dennismorello! Your library is amazing (I've starred it ⭐) and thanks for your time in reviewing the code.
